### PR TITLE
Parallel execution - v1.0.0

### PR DESCRIPTION
**Pull request by gkushang**
* Adding support to execute Cucumber features Parallel - its controlled by the user with flag to enable this feature
* User can enable Parallel execution by `options.executeParallel: true`
* If Parallel execution is requested then use cucumber runner from [parallel-cucumber](https://www.npmjs.com/package/parallel-cucumber)
* Number of workers can be defined through `options.workers`

### CODE REVIEW

**Comment by gkushang** [comment]
@mavdi can you please take a look?

**Comment by mavdi** [comment]
will release today but with ```0.8.0``` version. Any objections?

**Comment by gkushang** [comment]
yea, it should be fine 👍

**Comment by gkushang** [comment]
@mavdi please let me know if you want me to create a PR that changes the version to 0.8.0?

**Comment by gkushang** [comment]
@mavdi do you have any updates on release?

**Comment by mavdi** [comment]
Published, sorry for the delay.

**Comment by gkushang** [comment]
Awesome, thanks!

**Pull request merged**
