### PR TITLE
Support for debugger from IDE's like webstorm

### LINKED ISSUE #18: Support for debug.
Will it be possible to run grunt cucumber task in debug mode, so debugger can be attached from WebStorm or another IDE.

### PR DESCRIPTION
**Pull request by vkadam**
This will fix #18. Currently enabling debugger=true does not support html output. I will spend more time to  support html report in future. I am considering supporting multiple report formats.

But for now having support for debugging from IDE helps a lot. I will appreciate if you get this merged and published to npm.

### CODE REVIEW

**Comment by vkadam** [comment]
Also added beautification :)

**Comment by mavdi** [comment]
@vkadam can you please fix the merge conflicts?

**Comment by vkadam** [comment]
Conflicts resolved... :)

**Comment by vkadam** [comment]
Can you get it published to npm..

**Comment by mavdi** [comment]
Sorry for the delay, this has been release. ```v0.7.0```

**Pull request merged**
