### PR TITLE
Cucumber Parallel & Compiler option

### PR DESCRIPTION
**Pull request by gkushang**
* Adding a support to run Cucumber Features/Scenarios in Parallel for the Cucumber latest version
* Adding a support for `---compiler` option

### CODE REVIEW

**Comment by travi** [comment]
the `--compiler` option appears to be working, but I noticed that the extension extension portion of the [pattern](https://github.com/cucumber/cucumber-js#transpilers) seems to be ignored. I'm not sure if this is a result of this change or cucumber.js's handling of the input, but thought it would be worth mentioning.

For a bit more detail, I was originally worried because I need to compile both `.js` and `.jsx` extensions with babel and it didn't appear to support a list. I first tried `jsx:babel-register` and all the tests passed. I then tried `js:babel-register` and `js*:babel-register` with the same result. Being a little suspicious, I even tried `xml:babel-register` and everything passed.

**Comment by travi** [comment]
any update on getting this merged into a release?

**Comment by gkushang** [comment]
:+1:

**Comment by gkushang** [comment]
this has been tested pretty well - merging it :+1:

**Pull request merged**
